# Generated by Django 5.0.2 on 2024-02-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_phone_number_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='investor_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='startup_role',
        ),
    ]
