# Generated by Django 4.1 on 2024-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_authuser_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
