# Generated by Django 4.1 on 2024-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_companies_company_id_alter_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('position_name', models.CharField(max_length=100)),
                ('position_descr', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
