# Generated by Django 4.1 on 2024-02-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterField(
            model_name='companiesandusersrelations',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.positions'),
        ),
    ]
