# Generated by Django 4.1 on 2024-02-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_authuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='position_name',
            new_name='position',
        ),
    ]
