# Generated by Django 4.1 on 2024-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='edrpou',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]