# Generated by Django 4.1 on 2024-02-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_authuser_company_id_alter_authuser_email_and_more'),
        ('companies', '0003_rename_is_registered_companies_is_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesandusersrelations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser'),
        ),
    ]
