# Generated by Django 5.0.2 on 2024-02-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="company_id",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="investor_id",
            new_name="investor",
        ),
    ]
