# Generated by Django 5.0.2 on 2024-02-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_rename_company_id_subscription_company_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companies",
            old_name="is_registered",
            new_name="is_startup",
        ),
    ]
