# Generated by Django 5.0.2 on 2024-02-23 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_rename_is_registered_companies_is_startup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("is_startup", models.BooleanField(default=False)),
                ("common_info", models.TextField(blank=True)),
                ("contact_phone", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.CharField(blank=True, max_length=255)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("edrpou", models.IntegerField(null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("product_info", models.TextField(blank=True)),
                ("startup_idea", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="companiesandusersrelations",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="companiesandusersrelations",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.company"
            ),
        ),
        migrations.CreateModel(
            name="CompanyAndUserRelation",
            fields=[
                ("relation_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.CharField(
                        choices=[("H", "Head"), ("R", "Representative")], default="R"
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
