# Generated by Django 5.0.2 on 2024-02-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_alter_chat_participants_alter_message_recipient_and_more"),
        (
            "companies",
            "0006_company_remove_companiesandusersrelations_company_id_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompaniesAndUsersRelations",
        ),
        migrations.DeleteModel(
            name="Companies",
        ),
    ]
