# Generated by Django 4.1 on 2024-02-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_is_registered_companies_is_startup'),
        ('companies', '0007_delete_companiesandusersrelations_delete_companies'),
    ]

    operations = [
    ]
