# Generated by Django 5.0.2 on 2024-02-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_alter_chat_participants_alter_message_recipient_and_more"),
        (
            "companies",
            "0006_company_remove_companiesandusersrelations_company_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats", to="companies.companyanduserrelation"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="companies.companyanduserrelation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="companies.companyanduserrelation",
            ),
        ),
    ]
