# Generated by Django 5.0.2 on 2024-02-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechats', '0002_alter_conversation_initiator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
